<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="View/styles.css">
    <title>Twitter</title>
</head>

<body>
    <header id="header">
        <a class="logo" href="index.php">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
            </svg>
            <h1>twitter</h1>
        </a>
    </header>
    <div class="search-window">
        <form action="index.php?search=1&controller=search" method="POST">
            <input type="text" name="search-box" id="search-box">
            <input type="submit" value="Buscar">
        </form>
    </div>
    <div class="article-searched-window">
        <?php
        if ($articlesSearched) {
            foreach ($articlesSearched as $art) {
                echo '<article id="post-box">
                        <a id="perfil-box" href="">
                        <img id ="profile-pic" src="View/img/profile-pic.jpg">
                        <h6>' . $art->getAuthor()->getUsername() . '</h6>
                        </a>';
                echo '<h3>' . $art->getTitle() . '</h3>';
                echo '<p>' . $art->getText() . '</p>';
                echo '<section id="bottom-article-section">
                        <a class="comment-button" href="index.php?controller=comment&art=' . $art->getId() . '"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
                        <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"/>
                        </svg></a>
                        <p id="date">' . $art->getDate() . '</p>
                        </section>';
                echo '</article>';
            }
        }

        ?>
    </div>

</body>

</html>